# MAT 494 - 1.2 Homework


## NumPy
The built in lists in Python can be used for scientific computing purposes, but the NumPy library introduces functionality that makes it easier to conduct scientific computing using Python, such as n-dimensional arrays of homogeneous data types which allow for operations that are executed more efficiently.

In [2]:
import numpy as np
a1 = np.arange(15).reshape(3, 5) # creates a 1D array, then reshapes it into a 3x5 matrix
a2 = np.ones(4) # a 1D array with 4 one's
a3 = np.zeros(4) # same as above, but with zero's
a4 = np.array( [1, 2, 4, 3] ) # specify an array
print(a1)
print(a2)
print(a3)
print(a4)

# generate a 4x4 matrix with random values
a5 = np.random.randn(4, 4)
print(a5)

a6 = np.eye(5,5) # 5x5 matrix with one's along the diagonal and zero's everywhere else
# i.e., identity matrix
print(a6)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[1. 1. 1. 1.]
[0. 0. 0. 0.]
[1 2 4 3]
[[-0.27742221  0.21372473 -0.42998429  2.30125729]
 [ 0.9235406   1.59505079 -0.25998142 -0.34397396]
 [-1.12036081 -1.20926064 -0.39144646  0.00762121]
 [-0.08328764  0.00542761  0.74706593 -0.61719639]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


## 1.2.1 Linear Spaces
A linear subspace of V is a subset U ⊆ V that is closed under vector addition and scalar multiplication.
The zero vector is always in a linear subspace.

A span is a set of all linear combinations of a list of vectors.
As such, every span is a linear subspace.

A list of vectors is linearly independent if none of them can be written as a linear combination of the others.

One way to check if a list of vectors (v1, v2, ... vn) is linearly independent is if the vector equation

x1v1 + x2v2 + x3v3 + ... + xnvn = 0

Has only the trivial solution (i.e. x = 0 vector)

In [ ]:
# a, b, c are not linearly independent because a = b + c
a = np.array( [1, 2, 4] )
b = np.array( [1, 0, 2] )
c = np.array( [0, 2, 2] )
print(a)
print(b + c)

[1 2 4]
[1 2 4]


A basis of a linear subspace U is a list of vectors in U that span U and are linearly independent.
This means that a basis provides a unique representation fo the vectors in a subspace.

## 1.2.2 Orthogonality
A list of vectors {v1, ... vm} is orthonormal if the vectors are pairwise orthogonal (<vi, vj> = 0 when i != j) and each has norm 1 (<vi, vi> = 1 for all i).

## 1.2.3 Gram-Schmidt Process
The Gram-Schmidt algorithm is used to obtain an orthonormal base.
Letting a1, ..., am be linearly independent, we want to find an orthonormal basis for span(a1, ..., am).

NumPy has the algorithm included in its library:

In [ ]:
a = np.random.randn(5,4) # random 5x3 matrix
q, r = np.linalg.qr(a) # Gram-Schmidt Process
print(a)
print(q) # matrix of orthonormal vectors
print(r) # upper-triangular matrix

[[-1.30318245 -0.063435    0.93802656 -0.9930304 ]
 [ 0.58315649  0.73249437 -0.68380394  0.84637159]
 [-1.13720916  0.64837597  0.56042176  1.74833545]
 [ 0.43523162  2.64851413 -0.45096347 -0.03567873]
 [-0.02527863 -2.14386742  0.33744635 -1.54745674]]
[[-0.69443424 -0.08525363  0.20463754  0.66358724]
 [ 0.31074991 -0.16261964 -0.70035433  0.57817212]
 [-0.60599111 -0.27505794 -0.4105991  -0.42808484]
 [ 0.23192435 -0.72068414  0.49212086  0.10399182]
 [-0.01347037  0.6092981   0.2384381   0.17691255]]
[[ 1.8766103   0.52189752 -1.31263532 -0.09430149]
 [ 0.         -3.50704734  0.40768896 -1.45102011]
 [ 0.          0.          0.29928337 -1.90036716]
 [ 0.          0.          0.         -1.19552455]]


## 1.2.4 Eigenvalues and Eigenvectors
Let A be a square matrix. Then λ∈R is an eigenvalue of A if there exists a nonzero vector x such that Ax=λx, in which case x is an eigenvector.

Not every matrix has an eigenvalue, as seen in Example 1.2.22 from the lecture notes:


In [ ]:
A = np.array([ [0, -1], [1 ,0]])
lambdas, V = np.linalg.eig(A.T) # A.T produces the transposed matrix
print(lambdas) # no real solution
print(V)

[0.+1.j 0.-1.j]
[[0.70710678+0.j         0.70710678-0.j        ]
 [0.        +0.70710678j 0.        -0.70710678j]]


In general A will have at most d distinct eigenvalues, where d is the number of rows or columns in A.

## License
The MIT License (MIT)

Copyright (c) 2022 Joshua Tenorio