<a href="https://colab.research.google.com/github/joshtenorio/mat494-mathmethods-datasci/blob/main/1_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1.3 Homework
Linear regression is a useful tool in applications because of its simplicity.
In short, models depend linearly on unknown parameters, which means that these are easier to fit than models that are non-linearly related.
## 1.3.1 QR Decomposition
QR Decomposition is a useful way to solve the linear least squares problem.

The key idea is that you have a n x m matrix A, which is composed of an orthonormal basis span(a1, ..., am).
Letting Q be a n x m matrix Q=(q1,...,qm) we can write A=QR where R is an upper triangular and each column i of the matrix R contains the coefficients of the linear combination of qⱼ's that produce aᵢ's.

Note that aⱼ∈span(q1,...,qi), so column i of R has only zeros below the diagonal.

In [3]:
import numpy as np

A = np.random.randn(5,5) # random 5x5 matrix
Q, R = np.linalg.qr(A) # QR Decomposition via Gram-Schmidt Algorithm
print(A)
print(Q)
print(R) # note that this is upper triangle

[[-1.13234307  1.65169834 -2.16537751  1.19976014  0.77264743]
 [ 1.33590645  0.25109529 -0.11595815  0.37739557 -0.13005448]
 [ 0.16570369 -1.24316539 -1.1102972  -0.78104341 -0.49347246]
 [ 1.03502701  0.02182297 -0.67066276 -0.87364531 -0.81397834]
 [-0.38623854  0.60313376 -0.57042729 -1.12857168 -0.1954427 ]]
[[-0.54512917 -0.5832022  -0.51984     0.2965678  -0.06725552]
 [ 0.64312803 -0.43765283 -0.09244193  0.28475429  0.55246341]
 [ 0.07977257  0.59783725 -0.76187209  0.03963171  0.2328244 ]
 [ 0.49827956 -0.2506941  -0.36293272 -0.36137173 -0.65311581]
 [-0.18594179 -0.21926761 -0.09514001 -0.83594398  0.4577045 ]]
[[ 2.07720141 -0.93934684  0.78915196 -0.69908738 -0.91344771]
 [ 0.         -1.95409583  0.94303274 -0.86533088 -0.44179336]
 [ 0.          0.          2.2799496   0.36093148  0.30034614]
 [ 0.          0.          0.          1.69145457  0.63007952]
 [ 0.          0.          0.          0.          0.20345954]]


[[-1.13234307  0.54782914 -0.41023275 -0.20732681 

## 1.3.2 Least-Squares Problems
Suppose we want to solve Ax=b, and use Ax to approximate b.
First, let A∈R^{nxn} be a matrix and b∈Rⁿ be a vector.
We can use QR decomposition to solve the problem, but numpy also comes with a function to return a least-squares solution, which computes the vector x that solves the equation ax = b.

In [9]:
# data points we want to fit a line y=mx+b through
# we should expect to see m =~ 1 and b =~ -2
x = np.array([0, 1, 2, 3])
y = np.array([-2, -1.2, 0.1, 1.1])

# rewrite line equation as y=Ap, where A = [ [x 1] ] and p = [ [m], [b] ]
A = np.vstack([x, np.ones(len(x))]).T
print(A)
m, b = np.linalg.lstsq(A, y, rcond=None)[0] # np.lingalg.lstsq
m, b

[[0. 1.]
 [1. 1.]
 [2. 1.]
 [3. 1.]]


(1.0599999999999994, -2.0899999999999985)

## 1.3.3 Linear Regression
The common approach to solving linear regression problems involves finding coefficients that minimize ∑ᵢⁿ(yi-̂yi)^2.
This can be transformed into min(y-Aβ)^2, which is a least squares problem as described in 1.3.2.

## License
The MIT License (MIT)

Copyright (c) 2022 Joshua Tenorio