<a href="https://colab.research.google.com/github/joshtenorio/mat494-mathmethods-datasci/blob/main/1_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1.4 Homework
Principal Component Analysis is used for dimensionality reduction by projecting data points onto only the first few principal components. This obtains lower-dimensional data while preserving as much of the data's variation as possible. 
## 1.4.1 Singular Value Decomposition
The Singular Value Decomposition of a matrix has many applications, including data science and image processing.
It takes a `m x n` matrix `A` and decomposes it into three matrices: `U`, an `m x m` orthogonal matrix, Σ, a `m x n` matrix where the diagonal entries in `D` are the first `r` singular values of `A`, and an `n x n` orthogonal matrix `V` such that `A=U`Σ`V^T`.
The diagonal entries in Σ are the singular values for `A`.
numpy has functionality for computing SVD's:


In [4]:
import numpy as np
A = np.random.normal(size=[20,18])
U, sigma, V = np.linalg.svd(A, full_matrices=False)
A_a = np.matmul(np.matmul(U, np.diag(sigma)), V)
print(np.std(A), np.std(A_a), np.std(A - A_a))
print("Is A close to A_a?", np.isclose(A, A_a).all())

1.0240033876090764 1.024003387609076 1.6209937897127689e-15
Is A close to A_a? True


## 1.4.2 Low-Rank Matrix Approximations
Matrix norms allow us to talk about distances between two matrices.
The 2-norm of a matrix A∈Rⁿˣᵐ is


In [9]:
a = np.arange(9)
b = a.reshape((3,3))
print(b)
np.linalg.norm(b)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


14.2828568570857

Rank is the dimension of the vector space generated by the columns of a matrix A, which is also the maximum amount of linearly independent columns in A.